# Generated by Django 3.2.16 on 2023-05-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['author', '-pub_date']},
        ),
    ]
